include("time:util")
include("date:util")
include(":string-test-util")
include(":root-library")
include(":demo-library")
include(":app")
include(":mvvm:library")
include(":common:extensions:android-util")
include(":common:extensions:util")
include(":common:extensions:databinding-adapter")
include(":common:recyclerview:widget")
include(":common:progressbar:databinding")
include(":common:theme:android-util")
rootProject.name = "forma"
