include("time:util")
include("date:util")
include(":string-test-util")
include(":root-library")
include(":demo-library")
include(":app")
include(":mvvm:library")
include(":mvvm:databinding")
include(":common:recyclerview")
rootProject.name = "forma"
