# v3 Starlark call site — attributes only.
# gradlePath equivalent: :feature:calculator:impl  type=jvm.impl

load("//forma:defs.bzl", "jvm_impl")

jvm_impl(
    name = "impl",
    deps = [
        "//common/library:library",
        "//common/util:util",
        "//feature/calculator/api:api",
    ],
    visibility = [
        "//binary:__pkg__",
    ],
)
