# Progressive Android example
org.gradle.jvmargs=-Xmx2048m -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
# Configure all modules so co-located stub-impl siblings are validated even when
# not on the default production classpath (api+impl path).
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true
