# v3 Starlark call site — attributes only.
# gradlePath equivalent: :feature:greeter:impl  type=jvm.impl

load("//forma:defs.bzl", "jvm_impl")

jvm_impl(
    name = "impl",
    deps = [
        "//common/library:library",
        "//common/util:util",
        "//feature/greeter/api:api",
    ],
    visibility = [
        "//binary:__pkg__",
    ],
)
