# v3 Starlark call site — attributes only.
# gradlePath equivalent: :common:util  type=jvm.util

load("//forma:defs.bzl", "jvm_util")

jvm_util(
    name = "util",
    visibility = [
        "//binary:__pkg__",
        "//feature/greeter/impl:__pkg__",
        "//feature/calculator/impl:__pkg__",
    ],
)
