/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tools.forma.includer

import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Disabled
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'tools.forma.includer.greeting' plugin.
 */
class IncluderPluginTest {

    @Disabled
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("tools.forma.includer.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
