/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tools.forma.includer

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/**
 * A simple functional test includer plugin.
 */
class IncluderPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val rootBuildFile by lazy { projectDir.resolve("build.gradle.kts") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle.kts") }
    private val projectFile by lazy {
        File(projectDir, "app").mkdir()
        projectDir.resolve("app/build.gradle.kts")
    }

    @Test
    fun `include extra projects`() {
        // Set up the test build
        rootBuildFile.writeText("")
        projectFile.writeText("")
        settingsFile.writeText(
            """
            plugins {
                id("tools.forma.includer.greeting")
            }
        """.trimIndent()
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("projects")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Project ':app'"))
    }
}
